void addPeer(int  , int *);
int getPeerIndex(int );
void setupNeighbors(int  neighbors[][NUM_NEIGHBORS]);
void setupNeighborsBuffer(char *  , int*  , char *  , int  neighbors[][NUM_NEIGHBORS] , int );
void cleanNeighbors(int  , int  neighbors[][NUM_NEIGHBORS]);
void stampaComandi();
void stampaDettagli();
void stampaPeer(int * );
void stampaNeighbors(int neighbors[][NUM_NEIGHBORS] , int  , int * );
void removePeer(int  , int* );
void getNeighbors(int *);
void findNextNeighbor(int , int );