void addPeer(int peer_port , int *peer_list);
int getPeerIndex(int peer_port);
void setupNeighbors(int  neighbors[][NUM_NEIGHBORS]);
void setupNeighborsBuffer(char * buffer , int* len , char * msg , int  neighbors[][NUM_NEIGHBORS] , int index);
void cleanNeighbors(int sender_port , int  neighbors[][NUM_NEIGHBORS]);
void stampaComandi();
void stampaDettagli();
void stampaPeer(int * peer_list);
void stampaNeighbors(int neighbors[][NUM_NEIGHBORS] , int peer , int * peer_list);
void removePeer(int peer , int* peer_list);
void getNeighbors(int *updated);
void findNextNeighbor(int direction, int index);